version: "3"
networks:
  vote:
    driver: bridge

volumes:
   db-data:

services:
    vote:
      image: dhvnet/vote:master
      ports:
        - 5000:80
      networks:
        - vote
      depends_on:
        - redis

    redis:
      image: redis:alpine
      networks:
        - vote

    worker:
      image: dhvnet/worker:master
      networks:
        - vote
      depends_on:
        - redis

    db:
      image: postgres:9.4
      networks:
        - vote
      volumes:
        - "db-data:/var/lib/postgresql/data"
      environment:
        POSTGRES_PASSWORD: postgres

    result:
      image: dhvnet/result:master
      ports:
        - 5001:4000
      depends_on:
        - db
      networks:
        - vote
